embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
dropout: 0.8

query_num: [1, 2]
layer_num: 1
hidden_dropout_prob: [0.5, 0.8]

cic_neg_num: 16
cic_temperature: [0.5, 0.1]
cic_weight: 1e-03

hyper_parameters: ["hidden_dropout_prob", "cic_temperature", "query_num"]