embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: [0.0, 1e-05, 1e-04, 1e-03]

cf_model: lightgcn
mess_dropout: [0.1, 0.1]
n_layers: 1
knn_k: 10

learning_rate: [0.0001, 0.0005, 0.001, 0.005]

hyper_parameters: ["reg_weight", "learning_rate"]

